cmake_minimum_required(VERSION 3.16)
project(alfred_graph_export)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(Boost REQUIRED COMPONENTS serialization)
find_library(KARTO_LIBRARY kartoSlamToolbox REQUIRED PATHS /opt/ros/jazzy/lib)
add_executable(graph_export main.cpp)
target_include_directories(graph_export PRIVATE /opt/ros/jazzy/include ${EIGEN3_INCLUDE_DIRS})
ament_target_dependencies(graph_export rclcpp_lifecycle)
target_link_libraries(graph_export ${KARTO_LIBRARY} Boost::serialization)
install(TARGETS graph_export DESTINATION bin)
